name: dtest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
# perms needed for attestation workflow
permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tee
    steps:
    - name: Build artifact
      run: date > artifact.bin
    - name: Build Dockerfile
      run: |
          cat <<EOF > Dockerfile
          FROM scratch
          COPY artifact.bin .
          EOF
    - name: Setup qemu
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: notaryserverbuilds.azurecr.io
        username: notaryServerBuilds
        password: ${{ secrets.AZURE_CR_BUILDS_PW }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5.0.0        
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: notaryserverbuilds.azurecr.io/sgx:latest
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: notaryserverbuilds.azurecr.io/sgx:latest
        format: 'cyclonedx-json'
        output-file: 'sbom.cyclonedx.json'
    - name: get github to sign our measurement
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: notaryserverbuilds.azurecr.io/sgx/gramine7
        subject-digest: ${{ steps.push.outputs.digest }}
        sbom-path: 'sbom.cyclonedx.json'
        push-to-registry: true
