name: dtest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
# perms needed for attestation workflow
permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tee
    steps:
    - name: Setup qemu
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: notaryserverbuilds.azurecr.io
        username: notaryServerBuilds
        password: ${{ secrets.AZURE_CR_BUILDS_PW }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5.0.0        
      with:
        context: ./docker/base/gramine
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: notaryserverbuilds.azurecr.io/sgx:latest

    - name: get github to sign our measurement
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: notaryserverbuilds.azurecr.io/sgx/gramine7
        push-to-registry: true
