
name: tee

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SGX: 1

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: TEE
    steps:
    - name: azure-tee-build-${{ github.sha }}
      uses: appleboy/ssh-action@v1.0.3
      env:
          SEP: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: $GITHUB_REPOSITORY
          PORTZ: ${{  vars.AZURE_TEE_BUILD_PORT }}

      with:
         host: ${{ secrets.AZURE_TEE_BUILD_HOST }}
         username: ${{ secrets.AZURE_TEE_BUILD_USERNAME }}
         key: ${{ secrets.AZURE_TEE_BUILD_KEY }}
         port: ${{ secrets.SSH_PORT }}
         command_timeout: 10m
         allenvs: true
         script: |
            echo $SEP
            echo "NO"
            echo $GITHUB_REPOSITORY
            echo $GITHUB_REPO
            echo ${{ secrets.GITHUB_TOKEN }}
            echo ${{ env.AZURE_TEE_BUILD_PORT}}
            echo "hI!"
            cd /tmp 
            source $HOME/.cargo/env
            export RAWQUOTE=AA
            echo ${{ secrets.GITHUB_TOKEN }}
            curl -v -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $SEP" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$GITHUB_REPOSITORY/environments/TEE/variables/AZURE_TEE_BUILD_PORT -d '{"name":"AZURE_TEE_BUILD_PORT","value":"zz"}'
            curl -v -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$GITHUB_REPOSITORY/environments/TEE/variables/AZURE_TEE_BUILD_PORT -d '{"name":"AZURE_TEE_BUILD_PORT","value":"ss"}'
            exit 0
    - run: echo "${{ env.AZURE_TEE_BUILD_PORT }}"
    - run: echo $env:AZURE_TEE_BUILD_PORT
    - name: save quote from azure into env, write it to runner
      run: echo "${{ env.AZURE_TEE_BUILD_PORT }}" > /home/runner/work/_temp/sgx-build-quote.txt
    - name: upload it
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/_temp/sgx-build-quote.txt
    - name: get github to sign our measurement
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: /home/runner/work/_temp/sgx-build-quote.txt
